config.platform.queue = "expert"
config.platform.email = "#PBS -m be"
config.platform.scratchDirectory = "$USER_HOME/condor_scratch"
config.platform.loginHostName = "graphics2"
config.platform.utilityPath = "/opt/pbs/2021.1.1/bin"
