config.platform.queue = "normal"
config.platform.email = "#PBS -m be"
config.platform.scratchDirectory = "$USER_HOME/condor_scratch"
config.platform.loginHostName = "gordon.sdsc.edu"
config.platform.utilityPath = "/opt/torque/bin"
